name: dart_mock
description: A dart library that mimics mockjs. You can use this to analog network requests before the real interface is developed.
version: 2.0.1
homepage: https://github.com/zzzz1997/mock

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  intl: ">=0.17.0 <1.0.0"

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  flutter_lints: ^3.0.1
